<?php

namespace App\Presenters;

use Nette,
	App\Model;


/**
 * Base presenter for all application presenters.
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter
{

    public $config;

    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub

        $config = $this->context->parameters;
        $this->config = Nette\Utils\ArrayHash::from($config);
        $this->template->config = $this->config;

//        dump($this->config); die;


    }


}
