<?php
/**
 * Presenter, se stránkou přihlášení do aplikace
 *
 * @package LostPhone
 * @author Petr Sládek <xslade12@stud.fit.vutbr.cz>
 */

namespace App\Presenters;

use App\Model\Device;
use App\Model\Messages\RegistrationMessage;
use App\Model\User;
use Kdyby\Doctrine\EntityManager;
use Kdyby\Google\Google;
use Tracy\Debugger;


class SignPresenter extends BasePresenter
{

    /**
     * @var Google
     * @inject Pripojí se sám z DI contejneru
     */
    public $google;

    /** @var EntityManager @inject */
    public $em;

    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }


    /** @return \Kdyby\Google\Dialog\LoginDialog */
    protected function createComponentGoogleLogin()
    {
        $dialog = new \Kdyby\Google\Dialog\LoginDialog($this->google);
        $dialog->onResponse[] = function (\Kdyby\Google\Dialog\LoginDialog $dialog) {
            $google = $dialog->getGoogle();

            if (!$google->getUser()) {
                $this->flashMessage("Přihlášení se nezdařilo!", 'danger');
                return;
            }

            /**
             * If we get here, it means that the user was recognized
             * and we can call the Google API
             */

            try {
                $profile = $google->getProfile();
                if(!$me = $this->em->getRepository( User::getClassName() )->findOneBy(['googleEmail'=>$profile->getEmail()])) {
                    // Register from google
                    $me = new User();
                    $me->setGoogleEmail($profile->getEmail());
                    $me->setName($profile->getName());

                    $this->em->persist($me);
                    $this->em->flush();

                }

                // Nacte podle emailu vsechna zarizeni ktera jsou podle emailu jeho, ale jeste k n2mu nejsou prirazena
                /** @var $devices Device[] */
                $devices = $this->em->getRepository( Device::getClassName() )->findBy(['registrationMessage.googleAccountEmail'=>$me->getGoogleEmail(), 'owner' => null]);
                foreach($devices as $device)
                    $device->setOwner($me);
                $this->em->flush();

//
//                /**
//                 * You should save the access token to database for later usage.
//                 *
//                 * You will need it when you'll want to call Google API,
//                 * when the user is not logged in to your website,
//                 * with the access token in his session.
//                 */
//                $this->usersModel->updateGoogleAccessToken($google->getUser(), $google->getAccessToken());

                /**
                 * Nette\Security\User accepts not only textual credentials,
                 * but even an identity instance!
                 */
                $this->user->login($me->toIdentity());
                /**
                 * You can celebrate now! The user is authenticated :)
                 */

            } catch (\Exception $e) {
                Debugger::log($e, 'google');
                $this->flashMessage("Přihlášení se nezdařilo.", 'danger');
            }

            $this->redirect('Homepage:');
        };

        return $dialog;
    }



	public function actionOut()
	{
		$this->getUser()->logout();
		$this->flashMessage('You have been signed out.');
		$this->redirect('in');
	}

}
