<?php
/**
 * Created by PhpStorm.
 * User: Peggy
 * Date: 28.2.2015
 * Time: 11:50
 */

namespace App\Model\Commands;

use App\Model\Commands\Command;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;

/**
 * Class RingCommand
 * @package App\Model
 * @Entity
 */
class RingCommand extends Command {

    /**
     * @Column(type="integer")
     * @var int
     */
    protected $closeAfter = 0;

    /**
     * @return int
     */
    public function getType()
    {
        return Command::TYPE_RING;
    }

    /**
     * @return int
     */
    public function getCloseAfter()
    {
        return $this->closeAfter;
    }

    /**
     * Stop ringing after x miliseconds
     * @param int $miliseconds Miliseconds
     */
    public function setCloseAfter($miliseconds)
    {
        $this->closeAfter = (int) $miliseconds;
    }


    /**
     * Data ktera se poslou pres GCM na zarizeni
     * @return array
     */
    public function toGCMdata()
    {
        $data = parent::toGCMdata(); // TODO: Change the autogenerated stub
        $data['closeAfter'] = $this->closeAfter;

        return $data;
    }




}